In [2]:
import torch
import numpy as np
import torch.nn as nn

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
c = torch.tensor(a)
b = torch.tensor([[9,8,7],[6,5,4],[3,2,1]])
# concatenate
c = torch.cat((c[None, :, :],b[None, :, :]),0)
print(c)
print(c.shape)
c = torch.cat((c,b[None, :, :]),0)
print(c)
print(c.shape)
d = torch.tensor([])
d = torch.cat((d, b[None, :, :]),0)
print(d)

e = 1
np.repeat(e, 3)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
    def forward(self, x, y):
        x = x * y
        return x

net = Net()
net(2,3)

In [4]:
y = torch.tensor([1,2,3,4])
x = y[:, None]
z = torch.tensor([[1,1],[0,0],[0,0]])[None,...]
z_tmp = z[..., None, None, :]
*O, D = z_tmp.shape
# xz = z[...,0]*x
# yz = z[...,1]*y
print(x)
print(y)
# print(z)
# print('z_tmp=', z_tmp)
# print(xz)
# print(yz)
# print(xz+yz)
print('__________')
xz_tmp = z_tmp[...,0]*x
yz_tmp = z_tmp[...,1]*y
rslt = xz_tmp+yz_tmp
rslt = rslt.view(*O, -1)
# print(xz_tmp)
# print(yz_tmp)
print(rslt)
x.sin()

tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
__________
tensor([[[[[2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7, 5, 6, 7, 8]]],


         [[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]],


         [[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]]]])


tensor([[ 0.8415],
        [ 0.9093],
        [ 0.1411],
        [-0.7568]])

In [1]:
a = 1
def f(a):
    a = 2
    return a
b = f(a)
print(a)
print(b)

1
2


In [4]:
import torch
a = torch.tensor([1,2,3])
print(a.view(-1,1,1))
a.view(-1,1,1).expand(-1,3,3)

tensor([[[1]],

        [[2]],

        [[3]]])


tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]])

In [11]:
import numpy as np
a = np.array([])
b = np.array([1,2,3])
c = np.array([4,5,6])
a = np.append(a,b[None])
a = np.append(a,c[None])
print(a)

[1. 2. 3. 4. 5. 6.]
